version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - .:/app
      - /app/node_modules
    # Adicione healthcheck para garantir que o serviço está rodando
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3